#!/usr/bin/env bash
set -e

if command -v github_changelog_generator &>/dev/null; then
  github_changelog_generator
  git commit -m "Changelog for $npm_package_version" CHANGELOG.md
else
  echo Versioning requires you first run 'gem install github_changelog_generator' >&2
fi
