#!/usr/bin/env node

require('coffee-script/register')
require('babel-core/register')
var repl = require('repl')

console.log('💚  Let\'s play with testdouble.js!  💚')
global.td = require('../src')
global._ = require('lodash')
repl.start({prompt: 'td > ', useGlobal: true})


