#!/bin/bash

set -e

projects=${1-*/}

# Must be run from project root
cd examples
for D in $projects; do
  echo "<------ Running tests for example project '${D}'"
  cd "${D}"
  npm run --silent skip-ci || npm it --no-package-lock
cd ..
done
