export { default as function, default as func } from './function'
export { default as object } from './object'
export { default as constructor } from './constructor'
export { default as imitate } from './imitate'
export { default as when } from './when'
export { default as verify } from './verify'
export { default as matchers, Captor, Created } from './matchers'
export { default as replace } from './replace'
export { default as explain } from './explain'
export { default as reset } from './reset'
export { default as config, ConfigObject } from './config'
export { default as callback } from './callback'
export { default as version } from './version'
export { * as quibble } from 'quibble'
